### ISSUE TITLE
Are const object/arrays iterable?

### ISSUE THREAD

**Issue by robpalme** [rricard/proposal-const-value-types#27]
https://github.com/rricard/proposal-const-value-types/pull/25 clarified enumeration order, but did not say whether const things are iterable.

Can I do:

```
let constObj = #{ a:1, b:2 };
for (let i of constObj) { console.log(i) }

let constArr = #[ 1, 2 ];
for (let i of constArr) { console.log(i) }
```

**Comment by rricard** [comment]
I would say no, you can iterate with `Object.keys` or `Object.values` but it should be clarified indeed

**Comment by rricard** [comment]
Arrays should be iterable

**Comment by rickbutton** [comment]
agree, const objects not iterable, const arrays are

**Comment by rricard** [comment]
Basically, const variants should behave like the mutable variants when reading them but should be independent value types (see #24)
