### ISSUE TITLE
ConstMap and ConstSet

### ISSUE THREAD

**Issue by littledan** [rricard/proposal-const-value-types#3]
It may be useful to have deeply immutable Map and Set types. Should these be included in this proposal? Or a follow-on?

**Comment by ckknight** [comment]
They don't seem strictly necessary right now, as they could be represented (possibly suboptimally) as const arrays. Having `ConstMap` and `ConstSet` as a follow-on proposal seems like the best course of action. Including them this early could potentially lock one into an object creation syntax no one likes.

**Comment by mheiber** [comment]
The README now mentions const Map and Set as things that can be explored in a follow-on: https://github.com/rricard/proposal-const-value-types#are-there-any-follow-up-proposals-being-considered

Can we close this issue?
