### ISSUE TITLE
Const objects should *not* be valid weak map keys

### ISSUE THREAD

**Issue by isiahmeadows** [rricard/proposal-const-value-types#33]
This can essentially allow people to assign mutable state to an immutable object, and thus it should be disallowed for the same reasons it's not possible to use strings, symbols, numbers, booleans, `undefined`, or `null`. It's also consistent with the idea that `(const {a: 1}) === (const {a: 1})`, despite them being not necessarily physically identical.

**Comment by rickbutton** [comment]
Yep! Your reasoning is sound. We illustrated that point in the overview here: https://github.com/rricard/proposal-const-value-types#usage-in-mapsetweakmap

**Comment by ljharb** [comment]
Only objects can be weak; these are primitives.

**Comment by rickbutton** [comment]
Yep! @isiahmeadows see the above link for the explainer. I'll go ahead and close this as this is already discussed.

**Comment by isiahmeadows** [comment]
Yeah, forgot about it. Sorry for the noise!
