### ISSUE TITLE
Motivation to use with as a keyword and not as a method

### ISSUE THREAD

**Issue by Alexsey** [rricard/proposal-const-value-types#37]
After reading the proposal text I didn't find a single example where `with` operator would look different then `with` method:
```
const record2 = record1 with .b = 5;
// ->
const record2 = record1.with({b: 5});
```
```
const tuple2 = tuple1 with [0] = 2;
// ->
const tuple2 = tuple1.with({0: 2});
// or
const tuple2 = tuple1.with([2]);
```
```
assert((record with [k] = 5) === #{ a: 1, b: 5, c: 3});
assert((tuple with [i] = 2) === #[2, 2, 3]);
// ->
assert(record.with({[k]: 5}) === #{ a: 1, b: 5, c: 3});
assert(tuple.with({[i]: 2}) === #[2, 2, 3]);
```
```
const updatedData = marketData
    with [0].lastPrice = 195.891,
         [1].lastPrice = 286.61;
// ->
const updatedData = marketData.with([
    {lastPrice: 195.891},
    {lastPrice: 286.61},
]);
```
```
assert((#{} with .a = 1, .b = 2) === #{ a: 1, b: 2 });
assert((#[ {} ] with [0].a = 1) === #[ { a: 1 } ]);
assert((x = 0, #[ {} ] with [x].a = 1) === #[ { a: 1 } ]);
// ->
assert(#{}.with({a: 1, b: 2}) === #{ a: 1, b: 2 });
assert(#[ {} ].with([{a: 1}]) === #[ { a: 1 } ]);
assert((x = 0, #[ {} ].with({[x]: {a: 1}})) === #[ { a: 1 } ]);
```
```
record with .a = 1
record with .a = 1, .b = 2
tuple with [0] = 1
record with .a.b = 1
record with ["a"]["b"] = 1
// ->
record.with({a: 1})
record.with({a: 1, b: 2})
tuple.with([1])
record.with({a: {b: 1}})
record.with({["a"]: {["b"]: 1}})
```
```
assert(record === record2 with .a = 1);
// ->
assert(record === record2.with({a: 1});
```
```
let record2 = record with .c = 3;
record2 = record2 with .a = 3, .b = 3;
// ->
let record2 = record.with({c: 3});
record2 = record2.with({a: 3, b: 3});
```
```
const newState = state with .settings.theme = "dark";
// ->
const newState = state.with({settings: {theme: "dark"}});
```

It's arguable if `with` should accept `#{}`/`#[]` or `{}`/`[]`, but consider this open question just as a syntax difference

**Comment by davidsharp** [comment]
I take issue with the use of the `with` keyword for this (https://github.com/rricard/proposal-const-value-types/issues/1#issuecomment-502620070), and have equally not heard anything to convince me it's the correct approach.
I'd much prefer this, for it to be a method hanging off these new structures

**Comment by bmeck** [comment]
What is expected when a record has a `with` field if `with` is a special method?

```mjs
const rec = #{with: true};
console.log(rec.with); // ??
```

**Comment by ljharb** [comment]
any reason not to use `+`? `#{ a: 1 } + #{ b: 2 }` would yield `#{ a: 1, b: 2 }`

**Comment by Alexsey** [comment]
@bmeck I don't have a good answare to this question. But IMHO this is not enought to entroduce a new operator

@ljharb I was going to propose this just before creating this issue :) But I have changed my mind because it's the same as `...` and I'm not sure that it's ok to have two different operators for the same thing:
```
const c = #{ a: 1 } + #{ b: 2 }
// vs
const c = #{...{ a: 1 }, ...{ b: 2 }}
// or more realictic case. when a is already defined and we want to add b
const c = a + #{ b: 2 }
// vs
const c = #{ ...a, b: 2 }
```

**Comment by ljharb** [comment]
In that case, why would you need `with` at all, if you have spread?

**Comment by TehShrike** [comment]
> In that case, why would you need `with` at all, if you have spread?

That question has not yet been answered.

https://github.com/rricard/proposal-const-value-types/issues/1#issuecomment-502725556

**Comment by mheiber** [comment]
Thanks for the feedback!
This is an early-stage proposal and will morph a lot. We're hoping to focus on semantics first, as there is a lot of [Wadler's Law overhead potential](https://wiki.haskell.org/Wadler%27s_Law) with the proposal.

The semantics will be pretty tricky to get right!

**Comment by Alexsey** [comment]
I agree with @TehShrike - `with` is a good idea and I would also like to see it in the language, but it should not be limited to only #{}/#[]. I have thought more on this and I think I have something to add to already been said:
1. It's not `with` operator - it's ternary `a with b = c` because `=` is not acting here as assignment operator
2. It's different from `...` because type of it result is dinamically determines by `a` and not statically set by code
3. If we want to have immutable data structures to be widely used there should be a syntax that is as handy **as possible**

**Comment by mheiber** [comment]
@Alexsey would you be up for expanding the power of `with` in a follow-on proposal? We're trying to keep the proposal slim so it has a chance of advancing.

Maybe the experience of using `with` for immutable records in transpilers like Babel can inform future ergonomics quesions.

**Comment by TehShrike** [comment]
Aiming for slim seems like the best option, and not having `with` in this proposal at all seems like a good level of slimness.

**Comment by Alexsey** [comment]
@mheiber I would be happy to do that but would someone from TC39 provide support for the proposal that I would create? I mean I can not put it in the list of [Stage-0](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md) by my own

**Comment by mheiber** [comment]
@alexsey thanks! What about as a following once (if!)  this proposal makes it to stage 3?

**Comment by Alexsey** [comment]
@mheiber I'm good with any moment to start as long as I can assume that someone from TC39 would be interesting in linking it in [proposals](https://github.com/tc39/proposals) repo

**Comment by littledan** [comment]
We had `with` as a keyword for deep path updates. Now, it's a method on `Tuple.prototype` (records can simply use object spread), and the `with` keyword is broken out to be considered as a separate proposal.
