### ISSUE TITLE
Interactions with Symbols

### ISSUE THREAD

**Issue by robpalme** [rricard/proposal-const-value-types#39]
Assuming we want const values to allow efficient cloning across process boundaries, we need to define serialization.  How will Symbols be handled in this case?

**Comment by rricard** [comment]
Same goes with JSON conversion

**Comment by bmeck** [comment]
Are *all* symbols expected to be supported? Or only reproducible ones like those using `Symbol.forKey`? I think non-reproducable symbols would be odd to add to records themselves personally.

Per JSON, does this need to be serialized via JSON? Symbols are a type that don't serialize already, as is the case for other types.

**Comment by mheiber** [comment]
I suggest that lossless JSON roundtripping be added as a goal to this proposal, which would mean that symbols would not be allowed as keys or values in Records or as entries in Tuples.

Will PR for this in the next few days.

**Comment by kleinfreund** [comment]
What about `Symbol.iterator`/iteration protocols?
