### ISSUE TITLE
User-defined `@const` classes, and Temporal

### ISSUE THREAD

**Issue by littledan** [rricard/proposal-const-value-types#4]
I was imagining that we might have `@const class Point { x; y; }` declarations, which would declare a class that can then be "instantiated" as `@const(Point) { x: 1, y: 2 }`. I can understand if these are left for a future proposal, though.

If user-defined `@const` classes are left for later, I'd suggest that `Temporal` also shouldn't have special support for being considered const, since it's working towards a goal of being faithfully implementable in JavaScript. I'd suggest leaving this all for the future, and not blocking Temporal on this proposal.

**Comment by rricard** [comment]
We also need to explain the relation with BigInt as well

**Comment by rricard** [comment]
deferred for a followup proposal
