### ISSUE TITLE
Const objects and const arrays are primitives

### ISSUE THREAD

**Issue by littledan** [rricard/proposal-const-value-types#5]
Part of the idea I was thinking about for const objects and arrays is that they would be JavaScript "primitives", in the sense that TC39 has long been thinking about "value types". This has a few implications:
- They are not functions and cannot be called. So the constructor of a const class is an object. (It may be deeply frozen, though.)
- They are constructed with functions, and not with `new`. `new` always returns an object. If a constructor returns a primitive, the `this` value is used for the return value instead.
  - An implication of this is that `@const` classes will use callable constructors; maybe this could be done with a construct like `@const class Foo { @call constructor() { } }`
- Const objects and arrays cannot be used as keys in WeakMap, since those only have object keys
- Although `@const [] === @const []`, each time an object wrapper is made of them, it's unique: `Object(@const []) !== Object(@const [])`.

**Comment by rricard** [comment]
Ok, I think we made it clear we now handle value types! I'm going to close it!
