### ISSUE TITLE
Frozen prototypes and polyfilling ConstArray methods

### ISSUE THREAD

**Issue by littledan** [rricard/proposal-const-value-types#6]
`Array.prototype` sometimes gets new methods over time, so `ConstArray.prototype` may get additional methods. Polyfills fill the gap by adding these methods to existing prototypes. For this reason, I'm leaning towards `@const` classes not actually having frozen prototypes.

**Comment by rricard** [comment]
So here is how we landed: `null` prototype for Records (prev: const objects) and mutable prototype for Tuples (prev: const arrays).

Closing the issue
