### ISSUE TITLE
Document aspects of motivation and clarify semantics

### ISSUE THREAD

**Issue by littledan** [rricard/proposal-const-value-types#7]
This proposal makes a lot of decisions. Could you include in the README notes about why they were made? For example:
- Why are objects deeply immutable, and not allowed to point to mutable things?
- How does this relate to the decorators proposal?
- Why are the features included here important?
- What possible follow-on proposals could be made, and how would they build off of this proposal?

**Comment by mheiber** [comment]
Turning this into a checklist:

- [x] Why are objects deeply immutable, and not allowed to point to mutable things?
   - Disscussion of this topic continues here: https://github.com/rricard/proposal-const-value-types/issues/31
- [ ] How does this relate to the decorators proposal?
- [ ] Why are the features included here important? 
- [x] What possible follow-on proposals could be made, and how would they build off of this proposal?
    - [x] discussed in the README now: https://github.com/rricard/proposal-const-value-types#are-there-any-follow-up-proposals-being-considered

**Comment by rricard** [comment]
The overview section is here for you max! Closing this as we already have all of it.
