### ISSUE TITLE
JSON.stringify examples have incorrect output

### ISSUE THREAD

**Issue by elektronik2k5** [rricard/proposal-const-value-types#72]
- [x] My issue is not bikeshedding. (*we can bikeshed at a later proposal stage*)
- [x] My issue is not a request to add lots of stuff to the semantics. (*we can add things in follow-on proposals*)
- [x] My issue is appropriate for a stage 0 proposal and not too in-the-weeds.

A really minor issue:
`JSON.stringify(#{ a: #[1, 2, 3] });` should result in `'{"a":[1,2,3]}'` (and not `"{a: [1, 2, 3]}"`, as in the current example).
Same goes for the second example in https://github.com/rricard/proposal-const-value-types#jsonstringify

Happy to make a PR to fix it :)

**Comment by TehShrike** [comment]
PR away

**Comment by rricard** [comment]
merged the pr
